{% set name = "earth2observe" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/earth2observe/archive/{{ version }}.tar.gz
  sha256: fd89690e801a16aa92ca8c32d8e87be320f972b9c0c64b20288211a10bb2b23e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.14
    - pip >=22.3.1
  run:
    - python >=3.9,<3.15
    - numpy ==1.23.5
    - gdal >=3.5.3
    - netCDF4 >=1.6.1
    - pandas >=1.4.4
    - ecmwf-api-client >=1.6.3
    - earthengine-api >=0.1.324
    - joblib >=1.2.0
    - pyramids >=0.2.10
    - loguru >=0.6.0
    - pytest >=7.2.0
    - pytest-cov ==4.0.0
    - requests >=2.28.1


test:
  imports:
    - earth2observe

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
