{% set name = "earth2observe" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/earth2observe/archive/{{ version }}.tar.gz
  sha256: 51082d713b930cd0376a1bea493a7bffe12c8f52201402c3bc7e797e50761b2e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.12
    - pip >=22.2.2
    - poetry >=1.1.15
  run:
    - python >=3.9,<3.12
    - numpy >=1.23.2
    - pyramids >=0.2.6
    - ecmwf-api-client >=1.6.3
    - loguru >=0.6.0
    - joblib >=1.2.0
    - pandas >=1.4.4,<1.5.0
#    - netCDF4 >=1.5.5,<1.6.1
#    - gdal >=3.4.3,<3.5.1    


test:
  imports:
    - earth2observe

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
