{% set name = "earth2observe" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/earth2observe/archive/{{ version }}.tar.gz
  sha256: 42ade879f2d49e59684ec30039d42687f1b4eedebaebd7f64a41e4ecf884f46a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.11
    - pip >=22.3.1
  run:
    - python >=3.9,<3.11
    - numpy ==1.24.1
    - pip >=22.3.1
    - gdal >=3.5.3
    - netCDF4 >=1.6.1
    - pandas >=1.4.4
    - ecmwf-api-client >=1.6.3
    - earthengine-api >=0.1.324
    - boto3 >=1.26.50
    - joblib >=1.2.0
    - pyramids >=0.3.1
    - serapeum_utils >=0.1.1
    - loguru >=0.6.0
    - PyYAML >=6.0
    - pathlib >=1.0.1
    - requests >=2.28.1


test:
  imports:
    - earth2observe

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
